### ISSUE TITLE
Inventory in inventory datastring too long

### ISSUE THREAD

**Issue by nokosi1736** [gottsch/gottsch-minecraft-InterWorld-Bank#1]
Having a problem where on a server this mod gives me this code on connect
Internal Exception: io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than the maximum allowed (75 > 64) 
I do have a backpack mod on the server, 
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack

**Comment by gottsch** [comment]
On connect, you mean connecting to the server? So you can't even get into the game?

**Comment by gottsch** [comment]
I can't recreate this error. I'm using GottschCore, LegacyVault and Traveler's Backpack

**Comment by nokosi1736** [comment]
Ya, I can. See if I can find the log for you there was a lot of restarting
