### ISSUE TITLE
World locks up after opening up a vault.

### ISSUE THREAD

**Issue by Drakoflame** [gottsch/gottsch-minecraft-InterWorld-Bank#17]
Every time I re-open my vault on a new world, I can pull items out of it just fine, but after it closes (rather, I exit the inventory, the door stays open), I can't interact with anything in the world anymore. I can open my inventory, mobs move around, but I can't open chests, open block inventories, and open backpacks. 

https://pastebin.pl/view/0c2dfc90

**Comment by gottsch** [comment]
Can you reproduce and maybe grab the /logs/latest.log when it happens?
