### ISSUE TITLE
When stopping the server it stuck, never ends

### ISSUE THREAD

**Issue by ghost** [gottsch/gottsch-minecraft-InterWorld-Bank#5]
Forced to remove this mod due to impossibility to stop the server gracefully.
forge-1.16.5-36.1.32

'[1.16.5] SecurityCraft v1.8.22.2.jar'
 abnormals_core-1.16.5-3.2.0.jar
 AdChimneys-1.16.4-6.0.11.0-build.0144.jar
 additional_lights-1.16.4-2.1.3.jar
 AdFinders-1.16.4-5.0.9.0-build.0145.jar
 AdHooks-1.16.4-6.1.5.0-build.0124.jar
 AdLods-1.16.4-4.1.6.1-build.0145.jar
 alexsmobs-1.11.1.jar
 AmbientSounds_v3.1.9_mc1.16.5.jar
 appleskin-forge-mc1.16.x-2.0.0.jar
 AppleTreesRev-Forge-1.16.5-v1.3.jar
 Aquaculture-1.16.5-2.1.19.jar
 archers_paradox-1.16.4-1.2.0.jar
 architectury-1.20.28-forge.jar
 Artifacts-1.16.5-2.10.0.jar
 BackTools-1.16.5-10.1.0.jar
 BedBenefits-1.16.5-5.0.3.jar
 BetterMineshafts-Forge-1.16.4-2.0.4.jar
 BetterThirdPerson-Forge-1.16.4-1.5.1.jar
 Bookshelf-1.16.5-10.1.11.jar
 buildinggadgets-1.16.5-3.8.0.jar
 buzzier_bees-1.16.5-3.0.1.jar
 cakechomps-forge-1.16.4-5.0.0.2.jar
 carryon-1.16.5-1.15.5.15.jar
 Ceramics-1.16.5-1.6.3.jar
 cgm-1.0.1-1.16.3.jar
 chunkloaders-1.1.7-mc1.16.5.jar
 citadel-1.7.1-1.16.5.jar
 cleancut-mc1.16-2.2-forge.jar
 Clumps-6.0.0.25.jar
 CodeChickenLib-1.16.5-4.0.2.427-universal.jar
 cofh_core-1.16.4-1.2.1.jar
 comforts-forge-1.16.5-4.0.1.1.jar
 CommonCapabilities-1.16.5-2.7.0.jar
 compactmachines-4.0.0-beta.2.jar
 connectiblechains-1.2.0.jar
 CookingForBlockheads_1.16.5-9.3.3.jar
 CraftingTweaks_1.16.5-12.2.1.jar
 crashutilities-3.11.1.jar
 create-mc1.16.5_v0.3.2b.jar
 CreativeCore_v2.2.0_mc1.16.5.jar
 Cucumber-1.16.4-4.1.10.jar
 curios-forge-1.16.5-4.0.5.2.jar
 CyclopsCore-1.16.5-1.11.7.jar
 DarkUtilities-1.16.5-8.0.10.jar
 decorative_blocks-1.16.4-1.7.2.jar
 demagnetize-forge-1.16.2-1.2.2.jar
 Ding-1.16.5-1.3.0.jar
 DungeonCrawl-1.16.3-2.2.4.jar
 DynamicSurroundings-1.16.4-4.0.4.2.jar
 easy_villagers-1.16.5-1.0.11.jar
 EnchantmentDescriptions-1.16.5-7.0.12.jar
 EnderStorage-1.16.5-2.8.0.168-universal.jar
 endertanks-1.16-1.9.5.jar
 engineersdecor-1.16.4-1.1.13.jar
 ExCompressum_1.16.5-4.0.4.jar
 expandability-2.0.1-forge.jar
 extradisks-1.16.4-1.5.1.jar
 fairylights-4.0.5-1.16.5.jar
 fansmod-1.16.5-2.0.1.2.jar
 FastLeafDecay-v25.jar
 findme-1.16.3-2.2.0.0.jar
 Flopper-1.16.5-1.0.7.jar
 FluxNetworks-1.16.5-6.1.7.12.jar
 flywheel-1.16-0.1.0.jar
 ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar
 Fruitful-1.16.5-2.1.0.jar
 globalxp-1.16.5-v1.8.jar
 goldenhopper-1.2.0-1.16.3.jar
 gravestone-1.16.5-1.0.4.jar
 HydroGel-1.16.4-2.2.1.jar
 iChunUtil-1.16.5-10.4.1.jar
 ImmersiveEngineering-1.16.5-5.0.2-137.jar
 ImmersivePetroleum-1.16.5-3.3.0-5.jar
 industrial-foregoing-1.16.5-3.2.14.1-7.jar
 Inspirations-1.16.5-1.2.3.37.jar
 invtweaks-1.16.4-1.0.1.jar
 ironchest-1.16.4-11.2.10.jar
 item-filters-forge-1605.2.5-build.9.jar
 Jade-1.16.4-2.7.1.jar
 JAOPCA-1.16.5-3.4.0.9.jar
 jei-1.16.5-7.7.1.110.jar
 jumbofurnace-1.16.4-2.2.0.1.jar
 JustEnoughResources-1.16.5-0.12.1.121.jar
 longfallboots-1.6.0a.jar
 lootr-1.16.4-0.0.5.17.jar
 Mantle-1.16.5-1.6.109.jar
 mcjtylib-1.16-5.0.21.jar
 mcw-bridges-1.0.6-mc1.16.5.jar
 mcw-furniture-2.0.1-mc1.16.5.jar
 mcw-paintings-1.0.1-mc1.16.5.jar
 mcw-roofs-2.0.1-mc1.16.5-4.jar
 mcw-windows-1.0.3-mc1.16.5.jar
 Mekanism-1.16.5-10.0.21.448.jar
 MekanismGenerators-1.16.5-10.0.21.448.jar
 MekanismTools-1.16.5-10.0.21.448.jar
 metalbarrels-3.3a.jar
 mining_helmet-1.16.5-2.0.1.jar
 mob_grinding_utils-1.16.5-0.4.23.jar
 morered-1.16.5-2.1.1.0.jar
 MouseTweaks-2.14-mc1.16.2.jar
 mowziesmobs-1.5.19.jar
 MysticalAgradditions-1.16.4-4.1.5.jar
 MysticalAgriculture-1.16.4-4.2.0.jar
 mysticalworld-1.16.5-0.3.2.17.jar
 NaturesCompass-1.16.5-1.9.1-forge.jar
'Neat 1.7-27.jar'
'NefsMedievalPub+v0.9(1.16.5).jar'
 NetherPortalFix_1.16.3-7.2.1.jar
 obfuscate-0.6.2-1.16.3.jar
 omgourd-1.16.4-1.2.0.jar
 OreExcavation-1.8.157.jar
 PackingTape-1.16.3-0.10.0.jar
 Patchouli-1.16.4-53.1.jar
 pedestals-0.8s.jar
 personality-1.16.5-1.0.2.jar
 Placebo-1.16.4-4.5.0.jar
 pneumaticcraft-repressurized-1.16.5-2.13.1-202.jar
 polymorph-forge-1.16.5-0.25.jar
'Portable Nether-1.1.jar'
 QuantumStorage-1.16.4-5.3.0.jar
 quickteleports-1.16.2-1.1.2.jar
 rangedpumps-0.8.2.jar
 ReAuth-1.16-Forge-3.9.3.jar
 refinedstorage-1.9.13.jar
 relics-0.2.3.1.jar
 restrictions-1.16-3.0.3.jar
 rftoolsbase-1.16-2.0.11.jar
 rsgauges-1.16.4-1.2.10.jar
 Runelic-1.16.5-7.0.1.jar
 scuba-gear-1.16.5-1.0.3.jar
 selene-1.16.5-1.4.jar
 shetiphiancore-1.16-3.8.5.jar
 sodium-forge-2.9.1+rev.63112e3.jar
 SolarFluxReborn-1.16.3-16.2.5.jar
 sounddeviceoptions-1.4.2.jar
 Space-Bosstools-1.16.5-5.3.jar
 spark-forge.jar
 SpawnerFix-1.16.2-1.0.0.2.jar
 speedyhoppers-1.16.4-1.jar
 speedyladders-1.16.5-2.jar
 spiders-2.0-1.16.4-1.0.4.jar
 supermartijn642configlib-1.0.8-mc1.16.jar
 supplementaries-1.16.5-0.14.4f.jar
 swingthroughgrass-1.16.4-1.5.3.jar
 tanknull-2.3-1.16.4.jar
 titanium-1.16.5-3.2.8.4-10.jar
 torchmaster-2.3.7.jar
 torchslabmod-1.16.4_v1.6.19.jar
 tree_felling-2.3.jar
 twilightforest-1.16.5-4.0.490-universal.jar
 twoplayersonehorse-1.16.4-2.0.2.jar
 u_team_core-1.16.5-3.2.1.196.jar
 upgrade_aquatic-1.16.5-3.1.0.jar
 Uppers-0.3.2.jar
 upsizer-mc1.16.4-6.1.1.jar
 useful_railroads-1.16.5-1.4.6.38.jar
 walljump-forge-1.16.4-1.3.7.jar
 WaterStrainer-1.16.3-10.0.0.jar
 Waystones_1.16.5-7.6.2.jar
 Wither-Skeleton-Tweaks-1.16.4-5.3.0.jar
 WorldEdit-CUI-FE3-1.16.5-3.0.9.jar
 worldedit-mod-7.2.5-dist.jar
 Xaeros_Minimap_21.13.0_Forge_1.16.5.jar
 XaerosWorldMap_1.14.6.1_Forge_1.16.5.jar
 xnet-1.16-3.0.13.jar
 XNetGases-1.16.5-2.2.6.jar
 YungsApi-1.16.4-Forge-11.jar

**Comment by gottsch** [comment]
Fixed in v1.2.2
